name: "CI"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3.5.1"
        with:
          node-version: "18"
          cache: "npm"
      - run: "npm ci"
      - run: "npx eslint --max-warnings 0 ."
  format:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3.5.1"
        with:
          node-version: "18"
          cache: "npm"
      - run: "npm ci"
      - run: "npx prettier --check ."
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3.5.1"
        with:
          node-version: "18"
          cache: "npm"
      - run: "npm ci"
      - run: "npm test"
